spring:
  datasource:
    url: jdbc:mysql://rm-m5e5928rx3ho4giav.mysql.rds.aliyuncs.com:3306/zyqc_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: zyqchl
    password: Zyqc123456
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 10
    host: 120.78.164.178
    port: 6379
    timeout: 2000
    password: zyqc123456..
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

work:
  weixin:
    redirect-uri: http://authapi.heyikj68.com/auth/getCode
    agent-id: 1000027
    agent-secret: JXxb6wbSymclmbpPL3qMXhG907m-xYSZ9zgMAJFR630
