server:
  port: 8098

spring:
  profiles:
    active: dev
  application:
    name: oauth2-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  thymeleaf:
    cache: false

# OAuth2.0 配置
oauth2:
  token-expired: 1800
  exclude-path:
    - "/authorize/client"
    - "/authorize/password"
    - "/authorize/code"
    - "/authorize/login/**"
    - "/authorize/login"
    - "/authorize/verify/code/**"


mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.xaaef.authorize.server.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.xaaef.authorize.server.mapper: debug

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
